version: '3'
services:
  minecraft:
    image: papermc/paper:latest
    volumes:
      - minecraft_data:/data
    environment:
      EULA: 'true'
      VERSION: 1.19.2
      MC_VERSION: 1.19.2
    ports:
      - '25565:25565'
volumes:
  minecraft_data: